CONNECTIVITY_RULES = [
    {
        "id": "qsys_core_to_touchpanel_control",
        "category": "control",
        "source_roles": ["qsys"],
        "dest_roles": ["qsys-touchpanel"],
        "protocol": "tcp",
        "ports": [1710],
        "description": "Q-SYS Core to touch panel control",
        "required_level": "required",
        "scope": "same_vlan",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "crestron_processor_to_touchpanel_41794",
        "category": "control",
        "source_roles": ["crestron-processor"],
        "dest_roles": ["crestron-touchpanel"],
        "protocol": "tcp",
        "ports": [41794],
        "description": "Crestron processor to touch panel control",
        "required_level": "required",
        "scope": "same_vlan",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "crestron_processor_to_touchpanel_41796",
        "category": "control",
        "source_roles": ["crestron-processor"],
        "dest_roles": ["crestron-touchpanel"],
        "protocol": "tcp",
        "ports": [41796],
        "description": "Crestron processor to touch panel control",
        "required_level": "required",
        "scope": "same_vlan",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "uc_engine_to_crestron_touchpanel_49500",
        "category": "control",
        "source_roles": ["uc-engine"],
        "dest_roles": ["crestron-touchpanel"],
        "protocol": "tcp",
        "ports": [49500],
        "description": "UC engine to Crestron touch panel session",
        "required_level": "required",
        "scope": "same_vlan",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "uc_engine_to_crestron_touchpanel_49501",
        "category": "control",
        "source_roles": ["uc-engine"],
        "dest_roles": ["crestron-touchpanel"],
        "protocol": "tcp",
        "ports": [49501],
        "description": "UC engine to Crestron touch panel session",
        "required_level": "required",
        "scope": "same_vlan",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "crestron_processor_to_uc_engine_ssh",
        "category": "management",
        "source_roles": ["crestron-processor"],
        "dest_roles": ["uc-engine"],
        "protocol": "tcp",
        "ports": [22],
        "description": "Crestron processor to UC engine SSH management",
        "required_level": "required",
        "scope": "same_vlan",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "crestron_processor_to_samsung_display",
        "category": "control",
        "source_roles": ["crestron-processor"],
        "dest_roles": ["samsung-display"],
        "protocol": "tcp",
        "ports": [1515],
        "description": "Crestron processor to Samsung display control",
        "required_level": "required",
        "scope": "same_vlan",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "crestron_processor_to_novastar",
        "category": "control",
        "source_roles": ["crestron-processor"],
        "dest_roles": ["novastar"],
        "protocol": "tcp",
        "ports": [5200],
        "description": "Crestron processor to Novastar control",
        "required_level": "required",
        "scope": "same_vlan",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "barco_encoder_to_ctrl_8883",
        "category": "control",
        "source_roles": ["barco-encoder"],
        "dest_roles": ["barco-ctrl-server"],
        "protocol": "tcp",
        "ports": [8883],
        "description": "Barco encoder to CTRL server messaging",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "barco_decoder_to_ctrl_8883",
        "category": "control",
        "source_roles": ["barco-decoder"],
        "dest_roles": ["barco-ctrl-server"],
        "protocol": "tcp",
        "ports": [8883],
        "description": "Barco decoder to CTRL server messaging",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "barco_encoder_to_ctrl_8443",
        "category": "management",
        "source_roles": ["barco-encoder"],
        "dest_roles": ["barco-ctrl-server"],
        "protocol": "tcp",
        "ports": [8443],
        "description": "Barco encoder to CTRL server HTTPS management",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "barco_decoder_to_ctrl_8443",
        "category": "management",
        "source_roles": ["barco-decoder"],
        "dest_roles": ["barco-ctrl-server"],
        "protocol": "tcp",
        "ports": [8443],
        "description": "Barco decoder to CTRL server HTTPS management",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "barco_encoder_to_ctrl_7001",
        "category": "control",
        "source_roles": ["barco-encoder"],
        "dest_roles": ["barco-ctrl-server"],
        "protocol": "tcp",
        "ports": [7001],
        "description": "Barco encoder to CTRL server control",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "barco_decoder_to_ctrl_7001",
        "category": "control",
        "source_roles": ["barco-decoder"],
        "dest_roles": ["barco-ctrl-server"],
        "protocol": "tcp",
        "ports": [7001],
        "description": "Barco decoder to CTRL server control",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
    },
    {
        "id": "barco_encoder_to_decoder_media",
        "category": "media",
        "source_roles": ["barco-encoder"],
        "dest_roles": ["barco-decoder"],
        "protocol": "udp",
        "ports": [5004],
        "description": "Barco encoder to decoder media flow",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "UDP media flow is probe-limited from the current method.",
    },
    {
        "id": "barco_peer_5005",
        "category": "media",
        "source_roles": ["barco-encoder", "barco-decoder"],
        "dest_roles": ["barco-encoder", "barco-decoder"],
        "protocol": "udp",
        "ports": [5005],
        "description": "Barco peer media/control sync",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "Peer UDP flow is probe-limited from the current method.",
        "bidirectional": True,
    },
    {
        "id": "barco_decoder_to_decoder_322",
        "category": "control",
        "source_roles": ["barco-decoder"],
        "dest_roles": ["barco-decoder"],
        "protocol": "tcp",
        "ports": [322],
        "description": "Barco decoder peer control",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
        "bidirectional": True,
    },
    {
        "id": "barco_decoder_to_decoder_5893",
        "category": "control",
        "source_roles": ["barco-decoder"],
        "dest_roles": ["barco-decoder"],
        "protocol": "tcp",
        "ports": [5893],
        "description": "Barco decoder peer control",
        "required_level": "conditional",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
        "bidirectional": True,
    },
    {
        "id": "barco_decoder_to_decoder_8081",
        "category": "management",
        "source_roles": ["barco-decoder"],
        "dest_roles": ["barco-decoder"],
        "protocol": "tcp",
        "ports": [8081],
        "description": "Barco decoder peer web control",
        "required_level": "conditional",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
        "bidirectional": True,
    },
    {
        "id": "barco_ha_wireguard",
        "category": "ha",
        "source_roles": ["barco-ha-server"],
        "dest_roles": ["barco-ha-server"],
        "protocol": "udp",
        "ports": [51820],
        "description": "Barco HA server WireGuard sync",
        "required_level": "required",
        "scope": "cross_vlan",
        "feature_flag": None,
        "notes": "UDP HA validation is probe-limited from the current method.",
        "bidirectional": True,
    },
    {
        "id": "barco_ha_mqtt",
        "category": "ha",
        "source_roles": ["barco-ha-server"],
        "dest_roles": ["barco-ha-server"],
        "protocol": "tcp",
        "ports": [8883],
        "description": "Barco HA server secure messaging",
        "required_level": "required",
        "scope": "cross_vlan",
        "feature_flag": None,
        "notes": "",
        "bidirectional": True,
    },
    {
        "id": "barco_ha_https",
        "category": "ha",
        "source_roles": ["barco-ha-server"],
        "dest_roles": ["barco-ha-server"],
        "protocol": "tcp",
        "ports": [443],
        "description": "Barco HA server HTTPS sync",
        "required_level": "required",
        "scope": "cross_vlan",
        "feature_flag": None,
        "notes": "",
        "bidirectional": True,
    },
    {
        "id": "barco_ha_dns",
        "category": "ha",
        "source_roles": ["barco-ha-server"],
        "dest_roles": ["barco-ha-server"],
        "protocol": "udp",
        "ports": [53],
        "description": "Barco HA server DNS dependency",
        "required_level": "required",
        "scope": "cross_vlan",
        "feature_flag": None,
        "notes": "UDP DNS validation is probe-limited from the current method.",
        "bidirectional": True,
    },
    {
        "id": "dante_peer_audio_range",
        "category": "audio",
        "source_roles": ["dante-device"],
        "dest_roles": ["dante-device"],
        "protocol": "udp",
        "ports": ["14336-14600"],
        "description": "Dante audio streams",
        "required_level": "required",
        "scope": "l2_only",
        "feature_flag": None,
        "notes": "Multicast/L2-sensitive flow; current probing cannot prove full end-to-end delivery.",
        "bidirectional": True,
    },
    {
        "id": "dante_peer_ptp",
        "category": "audio",
        "source_roles": ["dante-device"],
        "dest_roles": ["dante-device"],
        "protocol": "udp",
        "ports": [319, 320],
        "description": "Dante PTP clocking",
        "required_level": "required",
        "scope": "l2_only",
        "feature_flag": None,
        "notes": "PTP is timing-sensitive and not fully provable from the current probe method.",
        "bidirectional": True,
    },
    {
        "id": "dante_peer_control",
        "category": "audio",
        "source_roles": ["dante-device"],
        "dest_roles": ["dante-device"],
        "protocol": "udp",
        "ports": [4440, 4444, 4455],
        "description": "Dante control and discovery",
        "required_level": "required",
        "scope": "l2_only",
        "feature_flag": None,
        "notes": "Discovery/control is multicast-sensitive and not fully provable from the current probe method.",
        "bidirectional": True,
    },
    {
        "id": "dante_peer_misc_range",
        "category": "audio",
        "source_roles": ["dante-device"],
        "dest_roles": ["dante-device"],
        "protocol": "udp",
        "ports": ["8700-8708"],
        "description": "Dante ancillary services",
        "required_level": "required",
        "scope": "l2_only",
        "feature_flag": None,
        "notes": "Ancillary UDP services are probe-limited from the current method.",
        "bidirectional": True,
    },
    {
        "id": "dante_peer_4321",
        "category": "audio",
        "source_roles": ["dante-device"],
        "dest_roles": ["dante-device"],
        "protocol": "udp",
        "ports": [4321],
        "description": "Dante optional service",
        "required_level": "conditional",
        "scope": "l2_only",
        "feature_flag": None,
        "notes": "Optional UDP service is probe-limited from the current method.",
        "bidirectional": True,
    },
    {
        "id": "dante_peer_mdns",
        "category": "audio",
        "source_roles": ["dante-device"],
        "dest_roles": ["dante-device"],
        "protocol": "udp",
        "ports": [5353],
        "description": "Dante mDNS service",
        "required_level": "conditional",
        "scope": "l2_only",
        "feature_flag": None,
        "notes": "mDNS is multicast-sensitive and not fully provable from the current probe method.",
        "bidirectional": True,
    },
    {
        "id": "tesira_control_host_to_biamp",
        "category": "control",
        "source_roles": ["tesira-control-host"],
        "dest_roles": ["biamp-device"],
        "protocol": "tcp/udp",
        "ports": [61451],
        "description": "Tesira control host to Biamp device",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "Mixed TCP/UDP validation is probe-limited from the current method.",
    },
    {
        "id": "biamp_peer_audio",
        "category": "audio",
        "source_roles": ["biamp-device"],
        "dest_roles": ["biamp-device"],
        "protocol": "udp",
        "ports": [12003],
        "description": "Biamp device-to-device audio/control",
        "required_level": "required",
        "scope": "either",
        "feature_flag": None,
        "notes": "UDP device-to-device validation is probe-limited from the current method.",
        "bidirectional": True,
    },
    {
        "id": "biamp_peer_61452_61453",
        "category": "control",
        "source_roles": ["biamp-device"],
        "dest_roles": ["biamp-device"],
        "protocol": "tcp",
        "ports": [61452, 61453],
        "description": "Biamp device peer control",
        "required_level": "conditional",
        "scope": "either",
        "feature_flag": None,
        "notes": "",
        "bidirectional": True,
    },
    {
        "id": "uc_engine_to_internet_http",
        "category": "internet",
        "source_roles": ["uc-engine"],
        "dest_roles": ["internet"],
        "protocol": "tcp",
        "ports": [80],
        "description": "UC engine outbound HTTP",
        "required_level": "required",
        "scope": "internet",
        "feature_flag": None,
        "notes": "Outbound internet validation is not directly proved by the current method.",
    },
    {
        "id": "uc_engine_to_internet_https",
        "category": "internet",
        "source_roles": ["uc-engine"],
        "dest_roles": ["internet"],
        "protocol": "tcp",
        "ports": [443],
        "description": "UC engine outbound HTTPS",
        "required_level": "required",
        "scope": "internet",
        "feature_flag": None,
        "notes": "Outbound internet validation is not directly proved by the current method.",
    },
    {
        "id": "uc_engine_to_internet_teams_media",
        "category": "internet",
        "source_roles": ["uc-engine"],
        "dest_roles": ["internet"],
        "protocol": "udp",
        "ports": [3478, 3479, 3480, 3481],
        "description": "UC engine Teams media ports",
        "required_level": "required",
        "scope": "internet",
        "feature_flag": None,
        "notes": "Outbound UDP media validation is not directly proved by the current method.",
    },
    {
        "id": "uc_engine_to_dns",
        "category": "internet",
        "source_roles": ["uc-engine"],
        "dest_roles": ["dns"],
        "protocol": "tcp/udp",
        "ports": [53],
        "description": "UC engine DNS resolution",
        "required_level": "required",
        "scope": "internet",
        "feature_flag": None,
        "notes": "DNS reachability is not directly proved by the current method.",
    },
    {
        "id": "uc_engine_to_ntp",
        "category": "internet",
        "source_roles": ["uc-engine"],
        "dest_roles": ["ntp"],
        "protocol": "udp",
        "ports": [123],
        "description": "UC engine NTP sync",
        "required_level": "required",
        "scope": "internet",
        "feature_flag": None,
        "notes": "NTP reachability is not directly proved by the current method.",
    },
    {
        "id": "xio_managed_device_to_internet_https",
        "category": "internet",
        "source_roles": ["xio-managed-device"],
        "dest_roles": ["internet"],
        "protocol": "tcp",
        "ports": [443],
        "description": "XiO-managed device outbound HTTPS",
        "required_level": "conditional",
        "scope": "internet",
        "feature_flag": None,
        "notes": "Outbound cloud validation is not directly proved by the current method.",
    },
]


def get_connectivity_rules():
    return [dict(rule) for rule in CONNECTIVITY_RULES]


def format_ports_for_display(ports):
    return ", ".join(str(port) for port in (ports or [])) or "-"
